CREATE TABLE IF NOT EXISTS cliente (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS chat (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    passo_atual VARCHAR(50),
    dados_contexto JSON,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    cliente_id INTEGER UNIQUE,
    FOREIGN KEY(cliente_id) REFERENCES cliente(id)
);